input_path: "scenarios_inputs/cheung_variants/"
input_file: "lifeboat2.json"
commit_hash: "e1cda3ea2bb0ca422d3775d7fbc911ba3e1efd3e"
output_path: "annotated_outputs/cheung_variants/"
scenario_ids: [1,2,3,4,5,6,7,8,9]
write_qualtrics: false
