input_path: "scenarios_inputs/cheung_variants/"
input_file: "lifeboat.json"
commit_hash: "288377cd1641f802c09f954c6670dd35c76c556e"
output_path: "annotated_outputs/cheung_variants/"
scenario_ids: [1,2]
steps_to_keep: ['beings','outcomes']
write_qualtrics: false
