input_path: "scenarios_inputs/moral_comp_exp4/"
input_file: "medication.json"
commit_hash: "64b4a6cf6437da95ba3941b1abe09d14afca26a9"
output_path: "annotated_outputs/moral_comp_exp4/"
scenario_ids: [1]
steps_to_keep: []
write_qualtrics: true
