input_path: "scenarios_inputs/nie/"
input_file: "nie_scenarios.json"
commit_hash: "5b20e2c520f3117263972c2aedade17c4b7e0174"
output_path: "annotated_outputs/nie/"
scenario_ids: [10,11,12,13,14,15,16,17,18,19,20]
write_qualtrics: false
