input_path: "scenarios_inputs/nie/"
input_file: "nie_scenarios.json"
commit_hash: "bfc528f045905d4e77fdf00667f1be18ca0ca6d0"
output_path: "annotated_outputs/nie/"
scenario_ids: [11,12,13,14,21,22,23,24,25]
write_qualtrics: false
